# Generated by Django 2.0.4 on 2019-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('corporateemail', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('numberemployees', models.CharField(max_length=20)),
                ('myrole', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
