# Generated by Django 2.0.4 on 2019-03-17 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_auto_20190317_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedcompanies',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='referencedcompanies',
            name='last_name',
        ),
        migrations.AddField(
            model_name='referencedcompanies',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedcompanies',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='corporateemail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='myrole',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='numberemployees',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
