# Generated by Django 2.0.4 on 2019-03-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20190317_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedcompanies',
            name='company',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='corporateemail',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='referencedcompanies',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
