# Generated by Django 2.0.4 on 2019-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_auto_20190317_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('defaultemail', models.CharField(max_length=50)),
                ('nifnumber', models.DecimalField(decimal_places=0, max_digits=9)),
                ('numberemployees', models.DecimalField(decimal_places=0, max_digits=9)),
                ('phonenumber', models.DecimalField(decimal_places=0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
