# Generated by Django 2.0.4 on 2019-04-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_auto_20190407_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idemployee', models.CharField(max_length=20)),
                ('voucherlocation', models.FileField(upload_to='documents/')),
                ('mntvoucher', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
                ('idcodecompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.Companies')),
            ],
            options={
                'verbose_name_plural': 'Vouchers',
            },
        ),
    ]
