# Generated by Django 2.0.4 on 2019-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='mntvoucher',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
