# Generated by Django 2.0.4 on 2019-04-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_auto_20190424_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='idcodecompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.Companies'),
        ),
    ]
