# Generated by Django 2.0.4 on 2019-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_auto_20190425_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
