# Generated by Django 2.0.4 on 2019-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_vouchers_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='id',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='idvoucher',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
