# Generated by Django 2.0.4 on 2019-04-26 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_auto_20190425_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='currency',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchers',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
