# Generated by Django 2.0.4 on 2019-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0018_messagescontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='numberwinnermonth',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
