# Generated by Django 2.0.4 on 2019-05-01 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pages', '0019_companies_numberwinnermonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('idwinner', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
                ('idcodecompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.Companies', to_field='idcode')),
                ('idemployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Winners',
            },
        ),
        migrations.AddField(
            model_name='vouchers',
            name='idwinner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Pages.Winners'),
            preserve_default=False,
        ),
    ]
