# Generated by Django 2.0.4 on 2019-05-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_auto_20190501_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='idwinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.Winners'),
        ),
    ]
