# Generated by Django 2.0.4 on 2019-05-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0022_auto_20190501_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='idcodecompany',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='idemployee',
        ),
        migrations.RemoveField(
            model_name='vouchers',
            name='idcodewinner',
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
