# Generated by Django 2.0.4 on 2019-05-05 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0024_auto_20190501_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='defaultemail',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='winners',
            name='idemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
