# Generated by Django 2.0.4 on 2019-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0025_auto_20190505_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdaymonth',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdayyear',
            field=models.DecimalField(decimal_places=0, default=1990, max_digits=4),
            preserve_default=False,
        ),
    ]
