# Generated by Django 2.0.4 on 2019-05-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0026_auto_20190505_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sexgender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
