# Generated by Django 2.0.4 on 2019-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0029_auto_20190512_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emailnotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonenotification',
            field=models.BooleanField(default=False),
        ),
    ]
