# Generated by Django 2.0.4 on 2019-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0030_auto_20190517_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccounts',
            fields=[
                ('iddeletedaccount', models.AutoField(primary_key=True, serialize=False)),
                ('motive', models.CharField(max_length=100)),
                ('othermotivedesc', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DeletedAccounts',
            },
        ),
        migrations.AddField(
            model_name='referencedcompanies',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
