# Generated by Django 2.0.4 on 2019-05-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0031_auto_20190518_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='idcodecompany',
        ),
        migrations.RemoveField(
            model_name='vouchers',
            name='idemployee',
        ),
    ]
