# Generated by Django 2.0.4 on 2019-05-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0032_auto_20190518_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAirlineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(max_length=2)),
                ('countrydescription', models.CharField(max_length=20)),
                ('airlinecompany', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CountryAirlineCompany',
            },
        ),
    ]
