# Generated by Django 2.0.4 on 2019-05-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0033_countryairlinecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryairlinecompany',
            name='airlinecompany',
            field=models.CharField(max_length=30),
        ),
    ]
