# Generated by Django 2.0.4 on 2019-05-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0034_auto_20190522_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlinecompany', models.CharField(max_length=30)),
                ('ranking', models.DecimalField(decimal_places=2, max_digits=2)),
                ('active', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AirlineCompanies',
            },
        ),
    ]
