# Generated by Django 2.0.4 on 2019-05-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0035_airlinecompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompanies',
            name='ranking',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
