# Generated by Django 2.0.4 on 2019-05-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0036_auto_20190524_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompanies',
            name='airlinecompany',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='countryairlinecompany',
            name='airlinecompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.AirlineCompanies', to_field='airlinecompany'),
        ),
    ]
