# Generated by Django 2.0.4 on 2019-06-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0037_auto_20190525_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
