# Generated by Django 2.0.4 on 2019-06-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pages', '0038_userprofile_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveldestination', models.CharField(max_length=20)),
                ('feedbackmessage', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifiedddate', models.DateTimeField(auto_now=True)),
                ('idemployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'FeedbackEmployees',
            },
        ),
    ]
